# Site settings
title: kpj's blog
email: kpjkpjkpjkpjkpjkpj@gmail.com
description: "foo"
baseurl: ""
url: "https://kpj.github.io/"
twitter_username: kpjkpj
github_username:  kpj

# Build settings
markdown: kramdown
permalink: pretty
include: ["_pages"]
exclude: ["README.md"]
highlighter: rouge

# Default values
defaults:
  -
    scope:
        path: ""
    values:
        author: "kpj"

# helpful stuff
indent: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
